version: "3.6"
services:
  GitlabRunner:
    image: gitlab/gitlab-runner:alpine
    environment:
     - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    command: register -n --name "DockerRunner" --url ${GITLAB_URL} --registration-token ${GITLAB_REGISTRATION} --tag-list docker --executor docker --docker-image docker:git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "gitlab-runner-etc:/etc/gitlab-runner"
      - "gitlab-runner-home:/home/gitlab-runner"
    networks:
      - core
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: any
        update_config:
          parallelism: 1
    
volumes:
  gitlab-runner-etc:
    external: true
  gitlab-runner-home:
    external: true
